### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by roccomuso** [reyiyo/virtual-serialport#10]
I found a few bugs:

1. the `this.open = true` replace the method `open()` with the same name. You'll no more have the open method then.. `this.open` might be renamed into `this.opened`.
2. the close method should set `this.opened `= false.
3. the `parsers` obj in the original `serialport` module is binded to the Class, not on the instance (it's a static function to be clear).

I'll be glad to help you fix a few other things if you add me as repo and npm contributor.

**Comment by nobusue** [comment]
+1

**Comment by djipco** [comment]
While we are it... version 4 of **serialport** changed its signature. The third parameter (autoOpen) is now part of the options.

**Comment by reyiyo** [comment]
@roccomuso thank you very much for the report! I've added you as a collaborator both in github and npm. Thank you for your help!

@cotejp this module is not updated with the 4.x version of serialport and it may be hard to maintain backwards compatibility. I think we should stop this version here and release a new major version fully compatible with serialport's 4.x API. We can continue this in #9
