### ISSUE TITLE
License compabilities

### ISSUE THREAD

**Issue by ecksun** [reyiyo/virtual-serialport#6]
I just noticed that [node-serialport is licensed under MIT](https://github.com/EmergingTechnologyAdvisors/node-serialport/blob/3c4f4512398d8b86dcba2b447bf9516b3d8b0ae7/package.json#L91) while [virtual-serialport is licensed under ISC](https://github.com/reyiyo/virtual-serialport/blob/f5b96088c1d4fb501cbd8bf84112ec4462ceb8f3/package.json#L28).

What does this mean in terms of taking code from node-serialport and including it in virtual-serialport?

I'm guessing the reason virtual-serialport is using the ISC license is because it is the default option when doing `npm init`, so perhaps that is something we should change, if we can. Can we? (I'm fine with my changes being licensed with MIT).

**Comment by reyiyo** [comment]
No problem from me! We can change it!

**Comment by reyiyo** [comment]
closed with 9bc49905ff7b50b04ce49a587e836d5653bc8def
